my-learning-app/src/main/java/C/mygitprojects/mylearningapp/application/beans/LoginBean.java
package C.mygitprojects.mylearningapp.application.beans;

public class LoginBean {
	private String email;
	private String password;

	public LoginBean() {
		super();
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}

my-learning-app/src/main/java/C/mygitprojects/mylearningapp/application/beans/QuestionBean.java
package C.mygitprojects.mylearningapp.application.beans;

public class QuestionBean {

	private String title;
	private String content;

	public QuestionBean() {

	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

}

my-learning-app/src/main/java/C/mygitprojects/mylearningapp/application/beans/RegisterBean.java
package C.mygitprojects.mylearningapp.application.beans;

import java.util.Date;

public class RegisterBean {
	private String name;
	private String email;
	private Date entryDate;
	private String password;
	private String secondPassword;

	public RegisterBean() {
		super();
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getEntryDate() {
		return entryDate;
	}

	public void setEntryDate(Date entryDate) {
		this.entryDate = entryDate;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSecondPassword() {
		return secondPassword;
	}

	public void setSecondPassword(String secondPassword) {
		this.secondPassword = secondPassword;
	}

	
	

}

my-learning-app/src/main/java/C/mygitprojects/mylearningapp/application/model/Question.java
package C.mygitprojects.mylearningapp.application.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.CreationTimestamp;

@Entity
@Table(name = "questions")
public class Question {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	@Column
	private String title;

	@Column
	private String content;

	@Column
	@CreationTimestamp
	private Date date;

	@ManyToOne
	private Professor professor;

	@OneToMany(mappedBy = "question")
	private List<Response> response = new ArrayList<>();

	public Question() {
		super();
	}

	public Question(String title, String content, Professor professor) {
		super();
		this.title = title;
		this.content = content;
		this.professor = professor;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public Professor getProfessor() {
		return professor;
	}

	public void setProfessor(Professor professor) {
		this.professor = professor;
	}

	public List<Response> getResponses() {
		return response;
	}

	public void setQuestion(List<Response> response) {
		this.response = response;
	}

}

my-learning-app/src/main/java/C/mygitprojects/mylearningapp/application/controller/LoginController.java
package C.mygitprojects.mylearningapp.application.controller;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import C.mygitprojects.mylearningapp.application.beans.LoginBean;
import C.mygitprojects.mylearningapp.application.dao.ProfessorDao;
import C.mygitprojects.mylearningapp.application.model.Professor;


@Controller
public class LoginController {
	
	@Autowired
	private ProfessorDao professorDao;
	
	@Autowired
	private HttpSession httpSession;

	@GetMapping(value = "/signin")
	public String showForm(Model model) {
		model.addAttribute("userLogin", new LoginBean());
		return "login";
	}

	@PostMapping(value = "/login")
	public String submit(@ModelAttribute("userLogin") LoginBean loginBean, Model model) {
		Professor u = professorDao.getByEmailAndPassword(loginBean.getEmail(), loginBean.getPassword());
		if (u != null) {
			httpSession.setAttribute("userLoggedIn", u);
			
		    return "redirect:/";
		} else {
			model.addAttribute("error","Error de validación");
			return "login";
		}
	}
	
	
	@GetMapping(value = "/logout")
	public String logout(Model model) {
		httpSession.removeAttribute("userLoggedIn");
		return "redirect:/";
	}
}

my-learning-app/src/main/java/C/mygitprojects/mylearningapp/application/controller/QuestionController.java
package C.mygitprojects.mylearningapp.application.controller;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;

import C.mygitprojects.mylearningapp.application.beans.QuestionBean;
import C.mygitprojects.mylearningapp.application.beans.ResponseBean;
import C.mygitprojects.mylearningapp.application.dao.QuestionDao;
import C.mygitprojects.mylearningapp.application.dao.ResponseDao;
import C.mygitprojects.mylearningapp.application.model.Professor;
import C.mygitprojects.mylearningapp.application.model.Question;
import C.mygitprojects.mylearningapp.application.model.Response;

@Controller
public class QuestionController {

	@Autowired
	private QuestionDao questionDao;

	@Autowired
	private ResponseDao responseDao;

	@Autowired
	private HttpSession httpSession;

	@GetMapping(value = "/my-questions")
	public String showForm(Model modelo) {
		modelo.addAttribute("questionbean", new QuestionBean());
		return "my-questions";
	}

	@PostMapping(value = "/submit/newquestion")
	public String submit(@ModelAttribute("questionbean") QuestionBean questionBean, Model model) {

		Question question = new Question();
		question.setContent(questionBean.getContent());

		Professor professor = (Professor) httpSession.getAttribute("userLoggedIn");
		question.setTitle(questionBean.getTitle());
		question.setProfessor(professor);
		questionDao.create(question);
		// autor.getPosts().add(post);

		return "redirect:/";
	}

	@GetMapping(value = "/question/{id}")
	public String detail(@PathVariable("id") long id, Model modelo) {

		modelo.addAttribute("questionbean", new QuestionBean());
		modelo.addAttribute("responsebean", new ResponseBean());
		// TESTS IF QUESTION EXISTS
		Question result = null;
		if ((result = questionDao.getById(id)) != null) {
			modelo.addAttribute("questionbean", result);
			modelo.addAttribute("responseForm", new ResponseBean());
			return "question";
		} else
			return "redirect:/";
	}

	@PostMapping(value = "/submit/newResponse")
	public String submitResponse(@ModelAttribute("responsebean") ResponseBean responseBean, Model model) {
	
		Professor professor = (Professor) httpSession.getAttribute("userLoggedIn");

		Response response = new Response();
		response.setProfessor(professor);


		Question question = questionDao.getById(responseBean.getQuestion_id());
		response.setQuestion(question);

		response.setContent(responseBean.getContent());
		responseDao.create(response);
		

		
		question.getResponses().add(response);
		professor.getResponses().add(response);

		//return "redirect:/post/" + responseBean.getQuestion_id();
		return "redirect:/question/" + responseBean.getQuestion_id();
	}

}

my-learning-app/src/main/java/C/mygitprojects/mylearningapp/application/controller/RegisterController.java
package C.mygitprojects.mylearningapp.application.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;

import C.mygitprojects.mylearningapp.application.beans.RegisterBean;
import C.mygitprojects.mylearningapp.application.dao.ProfessorDao;
import C.mygitprojects.mylearningapp.application.model.Professor;

@Controller
public class RegisterController {
	@Autowired
	private ProfessorDao professorDao;

	@GetMapping(value = "/signup")
	public String showForm(Model model) {
		model.addAttribute("userRegister", new RegisterBean());
		return "register";
	}

	@PostMapping(value = "/register")
	public String submit(@ModelAttribute("userRegister") RegisterBean r, Model model) {
		professorDao.create(new Professor(r.getName(), r.getEmail(), r.getPassword()));

		return "redirect:/";
	}
}

my-learning-app/src/main/webapp/WEB-INF/jsp/index.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8" session="true"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>myLearningApp</title>

<!--  STYLESHEETS -->
<jsp:include page="includes/imports-css.jsp" />
</head>
<body class="m-0">

	<!--  MAIN CONTAINER -->
	<div class="container-fluid p-0">

		<!--  HEADER IMAGE -->
		<jsp:include page="includes/static-content/header-image.jsp" />

		<!--  MAIN MENU -->
		<jsp:include page="includes/menu.jsp">
			<jsp:param name="home" value="home" />
		</jsp:include>

		<!--  WELCOME BANNER -->
		<jsp:include page="includes/welcome-block.jsp" />

		<!--  RANDOM BANNER -->
		<jsp:include page="includes/static-content/random-block.jsp" />

		<!--  QUESTIONS BANNER -->
		<jsp:include
			page="includes/static-content/questions-welcome-block.jsp" />

		<!--  QUESTIONS LIST -->
		<jsp:include page="includes/questions-list.jsp" />

		<!--  FOOTER -->
		<jsp:include page="includes/static-content/footer.jsp" />

	</div>

	<!--  JAVASCRIPT  -->
	<jsp:include page="includes/imports-js.jsp" />
</body>
</html>

my-learning-app/src/main/webapp/WEB-INF/jsp/login.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8" session="true"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>


<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>myLearningApp</title>

<!--  STYLESHEETS -->
<jsp:include page="includes/imports-css.jsp" />
</head>
<body>
	<!--  MAIN CONTAINER -->
	<div class="container-fluid p-0">

		<!--  HEADER IMAGE -->
		<jsp:include page="includes/static-content/header-image.jsp" />
		
		<!--  MAIN MENU -->
		<jsp:include page="includes/menu.jsp">
			<jsp:param name="login" value="login" />
		</jsp:include>


		<!--  LOGIN FORM -->
		<jsp:include page="includes/forms/login-form.jsp" />
		
		<!--  FOOTER -->
		<jsp:include page="includes/static-content/footer.jsp" />
	</div>

	<!--  JAVASCRIPT  -->
	<jsp:include page="includes/imports-js.jsp" />

</body>
</html>

my-learning-app/src/main/webapp/WEB-INF/jsp/my-questions.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8" session="true"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>myLearningApp</title>

<!--  STYLESHEETS -->
<jsp:include page="includes/imports-css.jsp" />
</head>
<body>

	<!--  MAIN CONTAINER -->
	<div class="container-fluid p-0">

		<!--  HEADER IMAGE -->
		<jsp:include page="includes/static-content/header-image.jsp" />
		
		<!--  MAIN MENU -->
		<jsp:include page="includes/menu.jsp">
			<jsp:param name="newquestion" value="newquestion" />
		</jsp:include>

		<!--  QUESTION FORM -->
		<c:if test="${not empty sessionScope.userLoggedIn }">
			<jsp:include page="includes/forms/question-form.jsp" />
		</c:if>

		<!--  FOOTER -->
		<jsp:include page="includes/static-content/footer.jsp" />

	</div>

	<!--  JAVASCRIPT  -->
	<jsp:include page="includes/imports-js.jsp" />
</body>
</html>

my-learning-app/src/main/webapp/WEB-INF/jsp/professorslist.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8" session="true"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>





<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>my Learning App</title>

<!--  STYLESHEETS -->
<jsp:include page="includes/imports-css.jsp" />
</head>
<body>

	<!--  MAIN CONTAINER -->
	<div class="container-fluid p-0">

		<!--  HEADER IMAGE -->
		<jsp:include page="includes/static-content/header-image.jsp" />

		<!--  MAIN MENU -->
		<jsp:include page="includes/menu.jsp">
			<jsp:param name="professors" value="professors" />
		</jsp:include>


		<!--  Professors List Block -->

		<div class="container-fluid m-5">
			<div class="row justify-content-center">
				<c:forEach items="${professors}" var="professors">
					<div class="card p-3 m-3" style="width: 20rem; border-color: #0275d8;">
						<img class="card-img-top mx-auto rounded-circle"
							src="http://i.pravatar.cc/150?u=${professors.email}"
							alt="Card image cap">
						<div class="card-block">
							<h4 class="card-title">${professors.name}</h4>
						</div>
						<ul class="list-group list-group-flush">
							<li class="list-group-item" style="border-color: #0275d8;">${professors.email}</li>
							<li class="list-group-item" style="border-color: #0275d8;"><fmt:formatDate
									pattern="dd/MM/yyyy" value="${professors.entryDate}" /></li>
						</ul>
					</div>
				</c:forEach>
			</div>
		</div>
	</div>

	<!--  FOOTER -->
	<jsp:include page="includes/static-content/footer.jsp" />

	<!--  Javascript  -->
	<jsp:include page="includes/imports-js.jsp" />



</body>
</html>

my-learning-app/src/main/webapp/WEB-INF/jsp/question.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8" session="true"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>myLearningApp</title>

<!--  STYLESHEETS -->
<jsp:include page="includes/imports-css.jsp" />
</head>
<body>

	<!--  MAIN CONTAINER -->
	<div class="container-fluid p-0">

		<!--  HEADER IMAGE -->
		<jsp:include page="includes/static-content/header-image.jsp" />
		

		<!--  MAIN MENU -->
		<jsp:include page="includes/menu.jsp" />

		<!--  QUESTION + RESPONSES -->

		<c:if test="${not empty questionbean.id }">
			<div class="jumbotron">
				<h1 class="display-3">${questionbean.title}</h1>
				<p class="lead">${questionbean.content}</p>
				<hr class="my-4">
				<c:forEach items="${questionbean.responses}" var="response">
					<div class="container bg-primary" style="color: white;">
						<p>Professor: ${response.professor.name}</p>
						<p>Response: ${response.content}</p>
					</div>
				</c:forEach>
			</div>
		</c:if>

		<!-- ADD RESPONSE FORM -->
		<c:if test="${not empty sessionScope.userLoggedIn }">
			<jsp:include page="includes/forms/response-form.jsp" />
		</c:if>

		<!--  FOOTER -->
		<jsp:include page="includes/static-content/footer.jsp" />

	</div>

	<!--  JAVASCRIPT  -->
	<jsp:include page="includes/imports-js.jsp" />
</body>
</html>

my-learning-app/src/main/webapp/WEB-INF/jsp/register.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8" session="true"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c"%>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>myLearningApp</title>

<!--  STYLESHEETS -->
<jsp:include page="includes/imports-css.jsp" />
</head>
<body>

	<!--  MAIN CONTAINER -->
	<div class="container-fluid p-0">

		<!--  HEADER IMAGE -->
		<jsp:include page="includes/static-content/header-image.jsp" />

		<!--  MAIN MENU -->
		<jsp:include page="includes/menu.jsp" />

		<!--  REGISTER FORM -->
		<jsp:include page="includes/forms/register-form.jsp" />

		<!--  FOOTER -->
		<jsp:include page="includes/static-content/footer.jsp" />
		
	</div>


	<!--  JAVASCRIPT  -->
	<jsp:include page="includes/imports-js.jsp" />
	<script>
		$(document).ready(function() {
			$("#register-form").validate();
		});
	</script>

</body>
</html>